name: test

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * *" # daily at 10:00 UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: savi-lang/action-install@v1

      - name: Create an example application
        run: |
          cat << EOF > manifest.savi
          :manifest bin "example"
            :sources "Main.savi"
          EOF
          cat << EOF > Main.savi
          :actor Main
            :new (env Env)
              env.out.print("Hello, World!")
          EOF
          savi run example

      - name: Build for all platforms
        id: example
        uses: ./
        with:
          manifest-name: example
          tarball-name: example-vX.Y.Z
          all-platforms: true
          macosx-accept-license: true
          windows-accept-license: true

      - name: Prove that the expected tarballs were built
        env:
          dir: spec-vX.Y.Z
        run: |
          cd ${{ steps.example.outputs.tarball-directory }}
          ls -la example-vX.Y.Z-x86_64-unknown-linux-gnu.tar.gz
          ls -la example-vX.Y.Z-x86_64-unknown-linux-musl.tar.gz
          ls -la example-vX.Y.Z-arm64-unknown-linux-musl.tar.gz
          ls -la example-vX.Y.Z-x86_64-unknown-freebsd.tar.gz
          ls -la example-vX.Y.Z-x86_64-apple-macosx.tar.gz
          ls -la example-vX.Y.Z-arm64-apple-macosx.tar.gz
          ls -la example-vX.Y.Z-x86_64-unknown-windows-msvc.tar.gz

      - name: Upload the tarballs as artifacts for download
        uses: actions/upload-artifact@v4
        with:
          name: release-tarballs
          path: ${{ steps.example.outputs.tarball-directory }}
